### ISSUE TITLE
Fields missing in users

### ISSUE THREAD

**Issue by numahell** [toulibre/PonyConf#14]
- if hosting needed
- type of hosting : hostel or couchsurfing

**Comment by bouttier** [comment]
Implemented in #17.
I think a select with three choices [ "no hosting needed", "hotel", "couhsurfing" ] is simpler than two boolean field "hosting needed" + "ok for couchsurfing" (and this last boolean makes no sence if "hosting needed" is not checked...). What is your opinion?

**Comment by numahell** [comment]
Yes ! for next version ?

**Comment by bouttier** [comment]
Ok :-)
I will try to write a migration as soon as I have some time.

**Comment by bouttier** [comment]
Done in c1d8fef1d246a32b95f648b0d88f4c4304d960b2 and a707e74e41f9142024261a7c1b5b4e589c77d436.
