### ISSUE TITLE
Cannot modify topic in edit form talk

### ISSUE THREAD

**Issue by numahell** [toulibre/PonyConf#15]
See snapshot

![talk-edit-form](https://cloud.githubusercontent.com/assets/546686/17496490/ddf6ba2c-5dbd-11e6-91e1-53af2c31fdee.png)

**Comment by nim65s** [comment]
It's not a bug, it's a feature x)
https://github.com/toulibre/PonyConf/blob/master/proposals/views.py#L50

@lporcheron : isn't it ?

**Comment by numahell** [comment]
haha :) 
but why ? admin cannot modify this neither.

**Comment by nim65s** [comment]
Well… This would change the reviewers, and some guy asking a question would not understand why he can't access to the discussion anymore, for example.

Moreover, those topics are just "tags" for the proposition, the real tracks will be defined later, depending on the propositions, with a OneToOne relation (we still need to add the model, btw).

And if reaaaally in a particular case we must change one topic, superadmins can do it in the dango admin.

**Comment by numahell** [comment]
Ok I did not know that the final tracks would be defined later. If it can be modified in django admin, I suppose that's fine, so we could close the issue. Ok for me then :)

**Comment by bouttier** [comment]
No new objection to this behaviour, I close!

**Comment by nim65s** [comment]
Anyway, this may be misleading. We should add a warning or something
