### ISSUE TITLE
Le nombre d'exposés dans un thème est visible par tout le monde

### ISSUE THREAD

**Issue by pulkomandy** [toulibre/PonyConf#19]
Bonjour,
https://participez-2016.capitoledulibre.org/topic/
Sur cette page, une fois connecté avec mon profil, je peux voir le nombre d'exposés proposé dans chaque thème. Mais, le lien pointe vers une page disant qu'aucun exposé n'est visible.

**Comment by lporcheron** [comment]
Bonjour,
Merci pour le retour, nous allons regarder le problème.
