### ISSUE TITLE
La liste des moyens de transports dans le profil a des entrées en double.

### ISSUE THREAD

**Issue by pulkomandy** [toulibre/PonyConf#20]
Dans mon profil (https://participez-2016.capitoledulibre.org/accounts/profile/), on me propose "covoiturage" et "carpooling", ainsi que "avion" et "plane". ça semble un peu redondant.

**Comment by lporcheron** [comment]
Merci, nous venons de corriger, il n'y a désormais plus que les termes en français.

**Comment by bouttier** [comment]
Il faudra également corriger le code : les entrées anglaises vont revenir au prochain migrate (elles sont créées via un signal post-migrate). Peut-être les créer uniquement s'il n'y a encore aucune au lieu de get_or_create.

**Comment by nim65s** [comment]
Sinon, on ne pourrait pas `get_or_create` uniquement celles qui correspondent à la langue du settings.py ?

**Comment by bouttier** [comment]
Pourquoi pas. À terme, le must serait de les localiser « à chaud » (i.e. suivant les préférences du browser du visiteur).

**Comment by bouttier** [comment]
J’ai re-modifié les données du français vers l’anglais, reste à passer en prod (cc @lporcheron) le commit b8f473edc6d51c096d252416ae5e19aa718e4dc7 qui s’occupe de les traduires à l’affichage.
