### ISSUE TITLE
La durée des conférences n'est pas indiquée

### ISSUE THREAD

**Issue by pulkomandy** [toulibre/PonyConf#21]
Quand on propose un exposé, on a le choix entre "short" et "long". Je suppose que c'est 20 et 45 minutes ou un truc du genre mais ça serait bien de le préciser.
D'autre part, les années précédentes il y avait une option "pas de préférence de durée", qui semble avoir disparu? (mais bon, si ça évite les gens qui disent pas de préférence, qui ont un slot de 20 minutes et qui parlent pendant 1h, c'est pas plus mal?)

**Comment by bouttier** [comment]
J’ai modifié l’outil pour que les types d’exposés soient facilement modifiables via la base de données (et donc qu’il soit facile de rajouter une durée explicite). Cependant, je n’ai pas plus d’info sur les durées donc je vais laisser un plannificateur expérimenter les spécifier !

**Comment by bouttier** [comment]
Les durées ont été ajoutées : 30 min pour les conférences courtes et 50 min pour les conférences longues. Je ferme, merci !
