### ISSUE TITLE
As a reviewer, how could I accept a proposition from an invited participant ?

### ISSUE THREAD

**Issue by numahell** [toulibre/PonyConf#22]
In french, en tant que reviewer d'une thématique, comment je peux valider la proposition d'un participant que l'on a invité ? Est-ce possible ? est-ce souhaitable ?

**Comment by bouttier** [comment]
Pas encore implémenté ! Mais on va faire ça rapidement, le boolean « accepté » existe déjà dans les models.
À priori, juste deux boutons « accepter » et « décliner » en dessous de la partie Vote. Cela déclencherai l’envoie d’une notification à la personne ayant proposé l’intervention. Ok sur le principe ? (je me demande surtout  si décliner une proposition par notification automatique n’est pas un peu ruste…)

**Comment by numahell** [comment]
Je suis d'accord, une notification automatique en cas de refus est un peu rustre :)
On peut peut-être rediriger vers un formulaire de message ?

**Comment by bouttier** [comment]
Très bien, une page de confirmation avec un textarea permettant d’envoyer un message à la personne ayant proposé l’intervention pour lui signifer l’acceptation ou le refus (textarea vide = pas de notification). Je m’occupe de cela dès que possible.

**Comment by bouttier** [comment]
Implémenté et déployé. N’hésite pas à ré-ouvrir l’issue s’il y a des problèmes ou des améliorations possibles !

**Comment by bouttier** [comment]
Youps : les notifications ne fonctionnent pas encore ! Je règle ça très bientôt.

**Comment by bouttier** [comment]
C’est réglé ! Implémenté dans 0108743d438583984badae7392174dfc6ff0ad66.
