### ISSUE TITLE
Éditer le titre et le thème des conférences

### ISSUE THREAD

**Issue by Zatalyz** [toulibre/PonyConf#26]
Bonjour,
J'ai renseigné une proposition de conférence. Après réflexion au sein de notre assoc, on m'a proposé de l'inscrire dans d'autres thèmes et de modifier le titre et... je peux tout modifier en dehors de ça. C'est bloqué par choix ? Ou est-ce un vrai bug ?

**Comment by nim65s** [comment]
Duplicate of #15

**Comment by nim65s** [comment]
Bonjour, et merci de ton retour.
Le mieux est de contacter les modérateurs pour qu’ils effectuent la modification que vous souhaitez.

Bon CdL :)

**Comment by Zatalyz** [comment]
Ah, désolé, je n'avais pas cherché dans les tickets fermés. merci :)
