### ISSUE TITLE
Custom avatar image is not shown in profile

### ISSUE THREAD

**Issue by wood-galaxy** [toulibre/PonyConf#29]
The uploading of a new avatar seem to work but the image is not displayed. (broken icone instead).
When trying to show the image, the pointing url is like : 
https://participez-2016.capitoledulibre.org/media/avatars/**username**/resized/160/**filename.jpg**
but return :
404 Not Found

**Comment by bouttier** [comment]
Fixed, thanks! That was a deployement issue.
