### ISSUE TITLE
Add the header Access-Control-Allow-Origin: * to the public program page

### ISSUE THREAD

**Issue by slestang** [toulibre/PonyConf#52]
In order to have the program dynamically generated on the main site of Capitole du Libre, we need to be able to make an Ajax request to the page:
https://participez-2016.capitoledulibre.org/planning/program/public/?format=xml

Currently it's failing because of CORS issue, adding the **Access-Control-Allow-Origin: *** header for this URL will fix the problem.

This is NOT an PonyConf issue, this concern the configuration of the Caddy web server.

**Comment by bouttier** [comment]
Should be ok, can you confirm?

**Comment by slestang** [comment]
Yes it's working, Thank.
