### ISSUE TITLE
Improve the XML program

### ISSUE THREAD

**Issue by slestang** [toulibre/PonyConf#54]
Several improvements should be made to the [XML program](https://participez-2016.capitoledulibre.org/planning/program/public/?format=xml) used by the Capitole du Libre mobile App and soon by the [programme page](https://2016.capitoledulibre.org/programme.html):

1. The person tag should have the firstname & lastname instead of the username
2. The type tag should be **Keynote**, **Conférence** or **Atelier** (from what I understand of the mobile app source code: [parser](https://github.com/toulibre/cdl-companion-android/blob/master/app/src/main/java/org/toulibre/cdl/parsers/EventsParser.java#L128), [Track](https://github.com/toulibre/cdl-companion-android/blob/master/app/src/main/java/org/toulibre/cdl/model/Track.java#L11), [strings](https://github.com/toulibre/cdl-companion-android/blob/master/app/src/main/res/values/strings.xml#L45)). It is currently **workshop** or **conférence (50 min)**.

May be we should add a new type for food/coffee break events, but that will required that we modify the Mobile app parser.

**Comment by bouttier** [comment]
1. Done
2. Done. The type tag is configured in the db so it will be easy to change them if needed. New types can also be added from django-admin if needed.

**Comment by slestang** [comment]
1. Good
2. I see that you change for **workshop** or **conference**. That works for me but I think it will required an update of the Mobile app to support **workshop** instead of **atelier**. May be we should just use **atelier**?

**Comment by bouttier** [comment]
sceen-chair interface problem, fixed ;-)

**Comment by slestang** [comment]
The new dynamic program is online and working fine. Thank.
