### ISSUE TITLE
Special chars should not be replaced by HTML codes in email text part

### ISSUE THREAD

**Issue by doug-letough** [toulibre/PonyConf#59]
In conversations/utils.py, notify_by_email() pass email data to render_to_string() for both HTML and text part of the multipart email message causing text part to be unreadable by text only email client users.

i.e:
```
tth &lt;noreply@tetalab.org&gt; a écrit :
&gt; il manque WTFPL dans la liste des licenses des vidéos.

Et c&#39;est une véritable honte, je regarde immédiatement comment
l&#39;ajouter.
```

**Comment by bouttier** [comment]
Fixed in 9a173809385f129bd8b64cea99935daa7b63c8b8
