### ISSUE TITLE
Missing WTF Public License in video licenses list

### ISSUE THREAD

**Issue by doug-letough** [toulibre/PonyConf#60]
For people that **really** don't care to be caught on picture or video, the **free** (as in *free as a bird*) license is http://www.wtfpl.net/ which is missing in the proposed licenses list.

**Comment by bouttier** [comment]
There is already the CC-0 licence, I do not see the need to add WTFPL.

**Comment by doug-letough** [comment]
echo $(wc -w cc-0.txt | cut -d' ' -f1)"-"$(wc -w wtfpl.txt | cut -d' ' -f1) | bc -l
993

It looks like there are 993 reasons to choose WTFPL but this is your choice.
