### ISSUE TITLE
Bad iCalendar encoding

### ISSUE THREAD

**Issue by alub** [toulibre/PonyConf#72]
I get a `UnicodeEncodeError` when trying to parse the ICS with `icalendar` on Python 2.7.12:
```
>>> import requests, icalendar
>>> r = requests.get('https://participez-2016.capitoledulibre.org/planning/program/public/?format=ics')
>>> icalendar.Calendar.from_ical(r.content)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/srv/http/webapp/venv/lib/python2.7/site-packages/icalendar/cal.py", line 336, in from_ical
    component.errors.append((None, str(e)))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u011e' in position 46: ordinal not in range(128)
```
It seems like the ICS file is not properly encoded.

This [ICS validator](http://severinghaus.org/projects/icv/?url=https%3A%2F%2Fparticipez-2016.capitoledulibre.org%2Fplanning%2Fprogram%2Fpublic%2F%3Fformat%3Dics) raises another issue: the newline format should be `\r\n` instead of `\n`.

Maybe use `icalendar` instead of templating? :)

**Comment by nim65s** [comment]
I didn't know this icalendar package… Maybe we should use it :)

**Comment by bouttier** [comment]
You really should: https://github.com/AFPy/pyconfr_2017/issues/7

**Comment by nim65s** [comment]
Thanks for the report, I'll fix this tonight :)

**Comment by nim65s** [comment]
```
In [1]: import requests, icalendar
   ...: r = requests.get('https://participez-2016.capitoledulibre.org/planning/program/public/?format=ics')
   ...: icalendar.Calendar.from_ical(r.content)
   ...: 
Out[1]: 
Calendar([('PRODID',
           vText('b'-//participez-2016.capitoledulibre.org//Capitole du Libre 2016//FR'')),
          ('X-WR-CALNAME', vText('b'PonyConf'')),
          ('X-WR-TIMEZONE', vText('b'Europe/Paris'')),
          ('VERSION', vText('b'2.0'')),
          ('CALSCALE', vText('b'GREGORIAN'')),
          ('METHOD', vText('b'PUBLISH''))])

```

What's your python version again ? :)

**Comment by nim65s** [comment]
ok, ok, I'll try to make this work on 2.7.

**Comment by nim65s** [comment]
Sorry if I’m a bit sarcastic tonight, but to quote RFC 5545, page 46:

>        ESCAPED-CHAR = ("\\" / "\;" / "\," / "\N" / "\n")
>          ; \\ encodes \, \N or \n encodes newline
>          ; \; encodes ;, \, encodes ,

**Comment by bouttier** [comment]
Try entering https://cfp.pycon.fr/schedule/ics on https://icalendar.org/validator.html
20 warnings, 127 errors
