### ISSUE TITLE
Session Chairman

### ISSUE THREAD

**Issue by nim65s** [toulibre/PonyConf#75]
Every talk should be introduced by someone, and this same person should be in charge of the timing.

In paperplaza (the IEEE Conference Management System), talks are grouped in sessions (room, startdate, duration, usually between 2 breaks), and sessions have co-chairmen.

**Comment by bouttier** [comment]
We already have sessions, but they do not have room / startdate / duration. I am not sure we should have it, this is restrictive (for instance, it is impossible to have two talks in two room at the same time, and some room constraints may require us to do so). For the records, current sessions already have managers.

**Comment by nim65s** [comment]
Yes, paperplaza's "sessions" are different form ponyconf's, as well as managers are different from chairmen :)

**Comment by bouttier** [comment]
This should probably part of a volunteers tasks assignment system, which is not planed for now, please re-open the issue if this feature is realy necessary.
