### ISSUE TITLE
Click on topic/../edit redirect to login form

### ISSUE THREAD

**Issue by numahell** [toulibre/PonyConf#8]
With numahell user, when I go to https://participez-2016-cdl.porcheron.info/topic/communs/edit/ redirect to login form : I only have reviewer rights for this topic. 
Maybe should redirect to an unauthorized message page ?

**Comment by bouttier** [comment]
You may want to grant some other users to help you or give a slightly different name to the topic. Looks ok for me, no?

**Comment by numahell** [comment]
Ok I know why it is strange to me. 
The link is on an information about responsible "1 responsible", it is more logical to get the list of the theme reponsibles. 
But the url topic/<name>/edit means I can reach edit page of the theme. 
It is a bit odd, isn't it ?
I'll try to propose another way to display this information.

**Comment by bouttier** [comment]
Solved by #8
