### ISSUE TITLE
Fix HTML in ICS calendars

### ISSUE THREAD

**Issue by alub** [toulibre/PonyConf#85]
As of now, the ICS produced by PonyConf can contain HTML entities in the SUMMARY and DESCRIPTION properties.

As per RFC 5545, sections [3.8.1.12](https://tools.ietf.org/html/rfc5545#section-3.8.1.12) and [3.8.1.5](https://tools.ietf.org/html/rfc5545#section-3.8.1.5), these should be plain text.

To provide HTML, secondary SUMMARY and DESCRIPTION properties could be added with an [alternate text representation parameter](https://tools.ietf.org/html/rfc5545#section-3.2.1).

**Comment by nim65s** [comment]
I guess we should start by providing a version in plain text :)

I'm on it.

**Comment by nim65s** [comment]
Following discussions with @bouttier & @alub we will just mark the content of the DB safe. It will replace all html entities. I just hope nobody will find some kind of injection with this.
